### ISSUE TITLE
How do you get the score file?

### ISSUE THREAD

**Issue by EdwardZH** [nusnlp/neuqe#2]
Do you get the F0.5 score file based on official evaluation code? I try to run it and it is very slow.

**Comment by shamilcm** [comment]
You could try to run it in multiple threads. It is very slow on some output sentences. Also, you have to calculate the score sentence by sentence.

**Comment by EdwardZH** [comment]
Thank you very much!

**Comment by gcunhase** [comment]
Since the score is calculated sentence by sentence, is it macro? If so, how could I get the micro F1 or F0.5 score?

**Comment by shamilcm** [comment]
F-score is computed using MaxMatch scorer. In the MaxMatch scorer, system edits are extracted such that it maximally matches with the human-marked gold edits. F-score is computed by comparing the system edits to gold edits.
See section 2.3 in the MaxMatch paper (https://www.aclweb.org/anthology/N12-1067) to see the F-score computation equation.
The only difference is that the score is calculated for each sentence for quality estimation. 

Not sure how exactly the definitions of micro/macro F-scores apply here as this is not a standard multi-class classification problem. It seems closer to the definition of micro F-score, since the true positives and other statistics are accumulated across all edits in the sentence/corpus.
